stages:
  - raw
  - intermediate
  - primary
  - feature_engineering
  - anomaly_detection
  - time_series

# Configuración común para todos los stages
.common_setup: &common_setup
  - apt-get update -y && apt-get install -y python3 python3-pip python3-venv
  - python3 -m venv analitica_cumplimiento
  - . analitica_cumplimiento/bin/activate
  - pip install --upgrade pip
  - pip install PyYAML==6.0.0
  - pip install pyarrow==15.0.0
  - pip install pandas==2.2.0
  - pip install fsspec==2024.6.1
  - pip install s3fs==2024.6.1
  - pip install boto3==1.34.155
  - pip install pillow==10.4.0
  - pip install matplotlib==3.5.0

# Instalación específica para el stage primary
.primary_setup: &primary_setup
  - *common_setup
  - pip install pycountry==24.6.1

# Instalación específica para el stage feature
.feature_engineering_setup: &feature_engineering_setup
  - *common_setup
  - pip install scikit-learn==1.5.0

# Instalación específica para el stage anomalias
.anomaly_detection_setup: &anomaly_detection_setup
  - *common_setup
  - pip install scikit-learn==1.5.0
  - pip install scipy==1.14.0

# Instalación específica para el stage series_tiempo
.time_series_setup: &time_series_setup
  - *common_setup
  - pip install numpy==1.26.0
  - pip install statsmodels==0.14.2

## Ejecución de los stages
raw_pipeline:
  image: "python:3.10.0"
  stage: raw
  before_script:
    - *common_setup
  script:
    - echo "INICIO PIPELINE RAW"
    - . analitica_cumplimiento/bin/activate
    - analitica_cumplimiento/bin/python3 __main__.py 'Pipeline Raw'
    - echo "FIN PIPELINE RAW"

intermediate_pipeline:
  image: python:3.10.0
  stage: intermediate
  before_script:
    - *common_setup
  script:
    - echo "INICIO PIPELINE INTERMEDIATE"
    - . analitica_cumplimiento/bin/activate
    - analitica_cumplimiento/bin/python3 __main__.py 'Pipeline Intermediate'
    - echo "FIN PIPELINE INTERMEDIATE"

primary_pipeline:
  image: python:3.10.0
  stage: primary
  before_script:
    - *primary_setup
  script:
    - echo "INICIO PIPELINE PRIMARY"
    - . analitica_cumplimiento/bin/activate
    - analitica_cumplimiento/bin/python3 __main__.py 'Pipeline Primary'
    - echo "FIN PIPELINE PRIMARY"

feature_engineering_pipeline:
  image: python:3.10.0
  stage: feature_engineering
  before_script:
    - *feature_engineering_setup
  script:
    - echo "INICIO PIPELINE FEATURE"
    - . analitica_cumplimiento/bin/activate
    - analitica_cumplimiento/bin/python3 __main__.py 'Pipeline Feature Engineering'
    - echo "FIN PIPELINE FEATURE"

anomaly_detection_pipeline:
  image: python:3.10.0
  stage: anomaly_detection
  before_script:
    - *anomaly_detection_setup
  script:
    - echo "INICIO PIPELINE ANOMALIAS"
    - . analitica_cumplimiento/bin/activate
    - analitica_cumplimiento/bin/python3 __main__.py 'Pipeline Anomaly Detection'
    - echo "FIN PIPELINE ANOMALIAS"

time_series_pipeline:
  image: python:3.10.0
  stage: time_series
  before_script:
    - *time_series_setup
  script:
    - echo "INICIO PIPELINE SERIES DE TIEMPO"
    - . analitica_cumplimiento/bin/activate
    - analitica_cumplimiento/bin/python3 __main__.py 'Pipeline Time Series'
    - echo "FIN PIPELINE SERIES DE TIEMPO"
