name: analitica_cumplimiento
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pyarrow=15.0.0
  - jupyter=1.0.0
  - ipykernel=6.29.0
  - pandas=2.2.0
  - openpyxl=3.1.0
  - numpy=1.26.0
  - pyyaml=6.0.0
  - scikit-learn=1.5.0
  - bayesian-optimization=1.4.3
  - seaborn=0.13.2
  - polars=1.4.1
  - fsspec=2024.6.1
  - s3fs=2024.6.1
  - boto3=1.34.155