name: analitica_cumplimiento
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pyarrow=15.0.0
  - jupyter=1.0.0
  - ipykernel=6.29.0
  - pandas=2.2.0
  - openpyxl=3.1.0
  - numpy=1.26.0
  - pyyaml=6.0.0
  - scikit-learn=1.5.0
  - seaborn=0.13.2
  - fsspec=2024.6.1
  - s3fs=2023.12.2
  - boto3>=1.28.0,<1.35.0
  - pycountry=24.6.1
  - diagrams=0.23.4
  - scipy=1.14.0
  - matplotlib=3.5.0
  - statsmodels=0.14.2
  - pillow=10.4.0